logistic Regression

In [ ]:
import pandas as pd
import numpy as np
data_preprocessed=pd.read_csv('df_preprocessed.csv')

In [ ]:
data_preprocessed.head(2)

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0

In [ ]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [ ]:
targets=np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [ ]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [ ]:
data_preprocessed['Excessive Absenteesim']=targets


In [ ]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [ ]:
#balanced Dataset

In [ ]:
data_with_targets=data_preprocessed.drop(['Absenteeism Time in Hours'],axis=1)

In [ ]:
data_with_targets.shape

(700, 15)

In [ ]:
unscaled_inputs=data_with_targets.iloc[:,:-1]

In [ ]:
from sklearn.preprocessing import StandardScaler
absenteesim_scaler=StandardScaler()

In [ ]:
#ignore
from sklearn.base import BaseEstimator,TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator,TransformerMixin):
  def __init__(self,columns,copy=True,with_mean=True,with_std=True):
    self.scaler=StandardScaler(copy,with_mean,with_std)
    self.columns=columns
    self.mean_=None
    self.var_=None

  def fit(self,X,y=None):
    self.scaler.fit(X[self.columns],y)
    self.mean_=np.mean(X[self.columns])
    self.var_=np.var(X[self.columns])
    return self
  def transform(self,X,y=None,copy=None):
    init_col_order = X.columns
    X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]),columns=self.columns)
    X_not_scaled=X.loc[:,~X.columns.isin(self.columns)]
    return pd.concat([X_not_scaled,X_scaled],axis=1)[init_col_order]


In [ ]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [ ]:
columns_to_scale=['Month Value','Day of the Week', 'Transportation Expense', 'Distance to Work','Age', 'Daily Work Load Average', 'Body Mass Index','Children', 'Pets']

In [ ]:
#ignore
absenteesim_scaler=CustomScaler(columns_to_scale)

TypeError: StandardScaler.__init__() takes 1 positional argument but 4 were given

In [ ]:
absenteesim_scaler.fit(unscaled_inputs)

StandardScaler()

In [ ]:
scaled_inputs=absenteesim_scaler.transform(unscaled_inputs)

In [ ]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [ ]:
scaled_inputs.shape

(700, 14)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [ ]:
print(x_train.shape,y_train.shape)

(560, 14) (560,)


In [ ]:
print(x_test.shape,y_test.shape)

(140, 14) (140,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [ ]:
reg=LogisticRegression()

In [ ]:
reg.fit(x_train,y_train)

LogisticRegression()

In [ ]:
reg.score(x_train,y_train)

0.7839285714285714

In [ ]:
## Manually check accuracy
model_outputs=reg.predict(x_train)
np.sum(model_outputs==y_train)/model_outputs.shape[0]

0.7839285714285714

In [ ]:
#Finding intercepts and coefficients


In [ ]:
reg.intercept_

array([-0.22206736])

In [ ]:
reg.coef_

array([[ 2.07601767,  0.33504757,  1.56162303,  1.32927434,  0.18793677,
        -0.07062253,  0.70639316, -0.03986811, -0.20089491, -0.00456366,
         0.31933564, -0.135508  ,  0.38172443, -0.3332426 ]])

In [ ]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [ ]:
feature_name=unscaled_inputs.columns.values

In [ ]:
summary_table=pd.DataFrame(columns=['Feature name'],data=feature_name)
summary_table['Coefficient']=np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0                  Reason_1     2.076018
1                  Reason_2     0.335048
2                  Reason_3     1.561623
3                  Reason_4     1.329274
4               Month Value     0.187937
5           Day of the Week    -0.070623
6    Transportation Expense     0.706393
7          Distance to Work    -0.039868
8                       Age    -0.200895
9   Daily Work Load Average    -0.004564
10          Body Mass Index     0.319336
11                Education    -0.135508
12                 Children     0.381724
13                     Pets    -0.333243

In [ ]:
summary_table.index=summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table=summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 Intercept    -0.222067
1                  Reason_1     2.076018
2                  Reason_2     0.335048
3                  Reason_3     1.561623
4                  Reason_4     1.329274
5               Month Value     0.187937
6           Day of the Week    -0.070623
7    Transportation Expense     0.706393
8          Distance to Work    -0.039868
9                       Age    -0.200895
10  Daily Work Load Average    -0.004564
11          Body Mass Index     0.319336
12                Education    -0.135508
13                 Children     0.381724
14                     Pets    -0.333243

In [ ]:
#interpretting the coefficients
summary_table['Odds_ratio']=np.exp(summary_table.Coefficient)

In [ ]:
summary_table

Feature name  Coefficient  Odds_ratio
0                 Intercept    -0.222067    0.800861
1                  Reason_1     2.076018    7.972656
2                  Reason_2     0.335048    1.398007
3                  Reason_3     1.561623    4.766551
4                  Reason_4     1.329274    3.778301
5               Month Value     0.187937    1.206757
6           Day of the Week    -0.070623    0.931814
7    Transportation Expense     0.706393    2.026668
8          Distance to Work    -0.039868    0.960916
9                       Age    -0.200895    0.817998
10  Daily Work Load Average    -0.004564    0.995447
11          Body Mass Index     0.319336    1.376213
12                Education    -0.135508    0.873272
13                 Children     0.381724    1.464808
14                     Pets    -0.333243    0.716596

In [ ]:
summary_table.sort_values('Odds_ratio',ascending=False)

Feature name  Coefficient  Odds_ratio
1                  Reason_1     2.076018    7.972656
3                  Reason_3     1.561623    4.766551
4                  Reason_4     1.329274    3.778301
7    Transportation Expense     0.706393    2.026668
13                 Children     0.381724    1.464808
2                  Reason_2     0.335048    1.398007
11          Body Mass Index     0.319336    1.376213
5               Month Value     0.187937    1.206757
10  Daily Work Load Average    -0.004564    0.995447
8          Distance to Work    -0.039868    0.960916
6           Day of the Week    -0.070623    0.931814
12                Education    -0.135508    0.873272
9                       Age    -0.200895    0.817998
0                 Intercept    -0.222067    0.800861
14                     Pets    -0.333243    0.716596

In [ ]:
#Testing

In [ ]:
reg.score(x_test,y_test)

0.7357142857142858

In [ ]:
predicted_proba=reg.predict_proba(x_test)
predicted_proba

array([[0.73864865, 0.26135135],
       [0.58845661, 0.41154339],
       [0.36763564, 0.63236436],
       [0.81198089, 0.18801911],
       [0.0613996 , 0.9386004 ],
       [0.30742403, 0.69257597],
       [0.29538175, 0.70461825],
       [0.08106026, 0.91893974],
       [0.80435611, 0.19564389],
       [0.76038732, 0.23961268],
       [0.46271934, 0.53728066],
       [0.15484755, 0.84515245],
       [0.04619732, 0.95380268],
       [0.72991038, 0.27008962],
       [0.23140393, 0.76859607],
       [0.55130442, 0.44869558],
       [0.5292476 , 0.4707524 ],
       [0.55522744, 0.44477256],
       [0.38197963, 0.61802037],
       [0.02527634, 0.97472366],
       [0.69617984, 0.30382016],
       [0.80458387, 0.19541613],
       [0.37734902, 0.62265098],
       [0.40003074, 0.59996926],
       [0.18229161, 0.81770839],
       [0.76011784, 0.23988216],
       [0.47050402, 0.52949598],
       [0.88997625, 0.11002375],
       [0.13577639, 0.86422361],
       [0.7969686 , 0.2030314 ],
       [0.

In [ ]:
predicted_proba.shape

(140, 2)

In [ ]:
predicted_proba[:,1]

array([0.26135135, 0.41154339, 0.63236436, 0.18801911, 0.9386004 ,
       0.69257597, 0.70461825, 0.91893974, 0.19564389, 0.23961268,
       0.53728066, 0.84515245, 0.95380268, 0.27008962, 0.76859607,
       0.44869558, 0.4707524 , 0.44477256, 0.61802037, 0.97472366,
       0.30382016, 0.19541613, 0.62265098, 0.59996926, 0.81770839,
       0.23988216, 0.52949598, 0.11002375, 0.86422361, 0.2030314 ,
       0.38454827, 0.70459151, 0.70138178, 0.56363893, 0.19541613,
       0.54256241, 0.20504956, 0.82072323, 0.44466019, 0.61108219,
       0.20908782, 0.40281153, 0.21373621, 0.09844091, 0.84224496,
       0.66612989, 0.71672931, 0.26982044, 0.20155736, 0.17070043,
       0.5733945 , 0.08298962, 0.67931742, 0.28630329, 0.87253409,
       0.48546569, 0.9325331 , 0.2462249 , 0.08169672, 0.08239341,
       0.72795552, 0.6695154 , 0.31201864, 0.86026294, 0.1838827 ,
       0.2596655 , 0.0131662 , 0.22029913, 0.8123649 , 0.31453865,
       0.20433741, 0.07128014, 0.93325923, 0.46319471, 0.65517

In [ ]:
#Saving the model
import pickle
with open('model','wb') as file:
  pickle.dump(reg,file)